### ISSUE TITLE
Update #82 Issue

### ISSUE THREAD

**Issue by flynfrank** [ELY3M/wX---modded-by-ELY-M#10]
@ELY3M Installed the #82 update and the app will not open, will not run. Cleared app cache and restarted the device with no luck. The wX app is currently 100% out of commission.

**Comment by flynfrank** [comment]
@ELY3M all. I've used the wX app for several years now and greatly appreciate it. The above issue in the #10 seems to be related to the RADAR feature of the app. My Note 20 Ultra will not allow me to install the previous #81 Update. Unfortunately, the app has stopped functioning until the bug is repaired.

**Comment by ELY3M** [comment]
you have to uninstall the #82 update than you can install #81   I have Samsung S21 Plus and it have been working fine.

**Comment by ELY3M** [comment]
what android version are you on?

**Comment by ELY3M** [comment]
I believe you have to clear your data and redo your settings.  in my debugging, I had to clear my data and redid my settings even I have my backups.  I know there are some changes in settings.

**Comment by flynfrank** [comment]
I'm on Android Version 12. When selecting the Lightening icon the app dies completely.

**Comment by flynfrank** [comment]
I saw the update versions in the Download folder. What is the manner of uninstalling Update #82? I tried just deleting the #82 and then running the #81 but it would not allow it.

**Comment by flynfrank** [comment]
I just tried your suggestion about deleting the data files. Event though I now have to reset everything, it does appear to be working. I will follow up if I continue having trouble. Thanks

**Comment by ELY3M** [comment]
Thank you for letting me know about lightening icon.  I have not tested that one.

**Comment by flynfrank** [comment]
The suggestion to delete the data files in Device/Settings/Apps/wX/Storage/Data appears to resolve the issue mentioned above within #82 Update.
