### ISSUE TITLE
#83 Update Spotter Network Key popup

### ISSUE THREAD

**Issue by flynfrank** [ELY3M/wX---modded-by-ELY-M#11]
After installing #83 Update a text image pops up randomly reminding the user to enter a Spotter Network Key number. If you do not have such an account, I found that entering 1234 worked to stop the ongoing popup. In doing this the Spotter feature seems to work the same as it has in the past prior to this update.

**Comment by ELY3M** [comment]
Thank you for letting me know.  I have to look more in this bug.

**Comment by ELY3M** [comment]
it is fixed in release #85
