### ISSUE TITLE
#83 Show/Hide Color Legend Bug

### ISSUE THREAD

**Issue by flynfrank** [ELY3M/wX---modded-by-ELY-M#12]
In version #83 the Show/Hide Color Legend appears to have a bug. 

From the Radar Screen/3 Dot Menu/Tools/ 

When selecting Show/Hide Color Legend the feature currently kills the app. 

I have tried clearing app Data Files, reloading backup settings, and again entering Locations, etc. I have also tried deselecting numerous options to see if the issue coexisted with another feature. None of what I tried had an impact on the issue itself.

**Comment by ELY3M** [comment]
Thank you for letting me know.  It is not crashing in #84 release.

**Comment by flynfrank** [comment]
I've loaded version #85 and went through the majority of the features. There appear to be no issues whatsoever and the app is running much faster, actually, better and faster than ever. Congrats! Thanks for spending time on this issue. 👍
