### ISSUE TITLE
Error when trying to open wX.

### ISSUE THREAD

**Issue by mikethalman** [ELY3M/wX---modded-by-ELY-M#20]
When I click the WX icon, I get an error stating this app need all files access to your phone memory or SD card to.
![Screenshot_20240622-105159](https://github.com/ELY3M/wX---modded-by-ELY-M/assets/44125097/a9a2ac87-623b-47d0-8397-67a3be900833)

**Comment by ELY3M** [comment]
yeah, google changing stuff all of the time....   I fixed it.  I thought I already uploaded new version.

**Comment by mikethalman** [comment]
Problem fixed, thanks.
