### ISSUE TITLE
App keeps crashing at launch

### ISSUE THREAD

**Issue by riddlecp** [ELY3M/wX---modded-by-ELY-M#3]
Pixel 4 XL, Android 10, December update, Build QQ1B.191205.012.A1

Previously working fine on my 2 XL. Great replacement for pykl3!

At install it asks for location and storage permissions. Granted. Then crashes. 

Any logs I can provide you?

**Comment by ELY3M** [comment]
I just saw this :(  can you get it to run again after crash?

**Comment by riddlecp** [comment]
So I started going down the list to see if anything was different between
the versions. I noticed that release 51 asks for different permissions -
instead of just location while application is running, it also asks for
regular all the time location access. This version will then come up. Going
to try to install updates to see if that allows newer ones to work.

**Comment by riddlecp** [comment]
Yeah, so really weird behavior. Installing release 51, and then upgrading to the latest version and clearing data allows me to pull up the application. Radar showing fine in everything that I'm testing.

**Comment by ELY3M** [comment]
let me know if you have anymore issues.
