### ISSUE TITLE
Unable to access Settings

### ISSUE THREAD

**Issue by flynfrank** [ELY3M/wX---modded-by-ELY-M#4]
Updated to version #63 and now not able to access app Settings. 
I start app everything appears to be functioning. Select 3-dots/Tools/Settings and the app dies and the screen returns to Home. In other words, the Setting page no longer loads.

**Comment by flynfrank** [comment]
As it appears to be the "Radar Settings" page that fails to open.

**Comment by ELY3M** [comment]
thank you, I will look in it.

**Comment by ELY3M** [comment]
I believe I fixed it in release #64   I hope this will help you.   please let me know if you still have issues.

**Comment by flynfrank** [comment]
Please include .apk file to #64 assests.

**Comment by ELY3M** [comment]
oops, I just do not notice that it was not uploaded for some reason.  I try to upload it again and it did uploaded ok.  

https://github.com/ELY3M/wX---modded-by-ELY-M/releases/download/64/app-release.apk

**Comment by flynfrank** [comment]
That worked. Thank You!!! Btw, I have been with this app from near the beginning. Your time and efforts spent with this app are greatly appreciated. I also recently installed the(#63) wX app on a Samsung Note 20 Ultra and the graphics look awesome. All app features worked flawlessly as well.

**Comment by ELY3M** [comment]
Thank you,  the #63 have bug :(   because I forgot one line of code for settings part.

**Comment by mikethalman** [comment]
Thanks 64 seems all good. Appreciate it.
