### ISSUE TITLE
VAD wind profile 

### ISSUE THREAD

**Issue by flynfrank** [ELY3M/wX---modded-by-ELY-M#9]
I’ve noticed two ongoing issues.
1)	Lower right/3dot/Level 3/NVW: VAD wind profile. 👈 Unable to access, 2-attempts shuts wX down.
2)	Lower 5-Button Navigation/Button 4-NOB and Button 5-NOG. 👈 No layer option appears, Select Play Button for either NOB or NOG displays text “Problem Downloading”. The remaining 3 Buttons function properly.

Request feature: The wX app is truly Badass! I’ve always thought it would be helpful to be able to scroll your animated frames in both directions. The current option is to Start, Stop, or Pause. The reason for this request is to better observe rotation within the clouds. Another goal with this request is to eventually observe in detail when & where the Phased Array optics radar system is being used. The electromagnetic waves should appear within at least one or more of the current product layers.

I use the wX app daily to expose weather control manipulation.

**Comment by ELY3M** [comment]
Thank you for your report on vad wind profile.   
not all Radars have NOB and NOG deployed yet.

**Comment by ELY3M** [comment]
the vad wind profile is fixed in release #81
